### PR TITLE
Add Dust2 transport

### PR DESCRIPTION
**Pull request by blanu**
Add Dust2 into master. This patch has been waiting to be merged for a while. Let me know if there is anything in particular that is holding this up that I can help with.

### CODE REVIEW

**Comment by Yawning** [comment]
What's holding this up, primarily is:
> I'm trying to figure out how to merge something like this, without putting the burden of having to package `github.com/blanu/Dust/tree/master/go` and `github.com/op/go-logging`.

Until I can come up with a good answer to that, I'm extremely reluctant to merge it, since without packages for bridge operators, no one will run Bridges that speak the new transport.

Debian's policy is that build time dependencies must have separate packages.  I am not a Debian developer, I do not want to be a Debian developer, and the current `obfs4proxy` package exists by the grace of the wonderful volunteer who handled packaging for me.

**Comment by blanu** [comment]
Is there something I could do to help with this?
Idea #1 - merge the dependencies into the obfs4proxy tree, then no dependencies
Idea #2 - remove the need for go-logging, although this will still leave us with the Dust package
Idea #3 - I can make a Dust package. Although this would need be be handed off to the obfs4proxy package maintainer for submission as I do not have the ability to submit packages.

**Comment by Yawning** [comment]
Removing go-logging should be easy, so it's the Dust dependency that I'm worried about.  Either idea 1 or 3 would work.  I have no strong preferences here, but I would prefer to minimize the work needed by the package maintainer if possible.

**Comment by blanu** [comment]
Okay great. Well there are no plans to use Dust outside of obfs4proxy anymore. Deployment as a PT is the new plan for how it will be used. So I will merge the Dust code into obfs4proxy.

**Comment by Yawning** [comment]
Sounds good to me.  Sorry for being a stickler wrt packaging issues, but things like this need to be easily deployable by volunteers, and having pre-built binary packages goes a long way.

**Comment by blanu** [comment]
I totally get it. In general, just tell me what you need and I'll make it happen!

**Comment by thomasf** [comment]
Personally I don't agree with the that part of the Debian packaging rules at all, in the end it still comes down to the notion of what/who owns/take responsibility of a snippet of code anyway. Even more relevant for Go where the notion of package versions generally doesn't even apply at all. I do understand why they want everything to be linkable and that they probably will end up in a complicated place if they start making exception. AFAIK the reason that Go 1.5 can build libraries as objects and use dynamic linking was Debian to begin with.. 

Also sorry for adding noise to your discussion...

**Review by detells111 — APPROVED** [review]

**Comment by Yawning** [comment]
This isn't going to happen, and it's languished here for years.

**Pull request closed without merging**
